name: Run Rfam SQL Query

on:
  push:
    paths:
      - 'query.sql'  # Триггер при изменении файла query.sql

jobs:
  run-sql-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install mysql-client

      - name: Run SQL query on Rfam
        env:
          MYSQL_HOST: mysql-rfam-public.ebi.ac.uk
          MYSQL_PORT: 4497
          MYSQL_DATABASE: Rfam
          MYSQL_USER: rfamro
        run: |
          mysql --host=$MYSQL_HOST --port=$MYSQL_PORT --user=$MYSQL_USER --database=$MYSQL_DATABASE < ./query.sql
